version: '3.8'
services:
  backend:
    image: my-spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database2.cn4mq8gki08p.us-east-1.rds.amazonaws.com:3306/jo2024
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    restart: on-failure
  frontend:
    image: my-react-app
    ports:
      - "3000:80"
    depends_on:
      - backend
